In [ ]:
T"""
Imagine you have a magic arrow (vector) that, when you transform it (using a matrix),
only gets longer or shorter but doesn’t change direction. This special arrow is called an eigenvector,
and the factor by which it’s stretched or shrunk is the eigenvalue.
For example, if you stretch a rubber band by a factor of 2,
the direction of the band is the eigenvector, and 2 is the eigenvalue.
"""

'\nImagine you have a magic arrow (vector) that, when you transform it (using a matrix), \nonly gets longer or shorter but doesn’t change direction. This special arrow is called an eigenvector, \nand the factor by which it’s stretched or shrunk is the eigenvalue. \nFor example, if you stretch a rubber band by a factor of 2, \nthe direction of the band is the eigenvector, and 2 is the eigenvalue.\n'

In [1]:
import numpy as np

# Define a matrix (transformation)
A = np.array([[5, 2],
              [2, 5]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:")
print(A)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors (as columns):")
print(eigenvectors)

# Test the eigenvector/eigenvalue property: A * eigenvector = eigenvalue * eigenvector
first_eigenvector = eigenvectors[:, 0]  # First column is the first eigenvector
first_eigenvalue = eigenvalues[0]

# Multiply A with the first eigenvector
result_left = np.dot(A, first_eigenvector)
# Multiply eigenvalue with the first eigenvector
result_right = first_eigenvalue * first_eigenvector

print("\nTesting A * eigenvector == eigenvalue * eigenvector:")
print("A * eigenvector:", result_left)
print("eigenvalue * eigenvector:", result_right)

Matrix A:
[[5 2]
 [2 5]]

Eigenvalues: [7. 3.]
Eigenvectors (as columns):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Testing A * eigenvector == eigenvalue * eigenvector:
A * eigenvector: [4.94974747 4.94974747]
eigenvalue * eigenvector: [4.94974747 4.94974747]


In [ ]:
"""
So you can see,

The matrix A transforms space.

The eigenvectors (columns of eigenvectors) are directions that don’t change when A is applied.

The eigenvalues (scalars) tell you how much each eigenvector is stretched.
"""

'\nSo you can see,\n\nThe matrix A transforms space.\n\nThe eigenvectors (columns of eigenvectors) are directions that don’t change when A is applied.\n\nThe eigenvalues (scalars) tell you how much each eigenvector is stretched.\n'

In [ ]:
"""
Assignment for You:

1. Modify the Matrix: Change the matrix A to [[3, 1], [1, 3]] and rerun the code.
What are the new eigenvalues and eigenvectors?

2. Verify Manually: Pick one eigenvector from the result and multiply it by A using pen-and-paper.
Check if it equals the eigenvalue times the eigenvector.

3. Real-World Connection: Think of a scenario where finding these "special directions" (eigenvectors)
might be useful (e.g., in computer graphics or physics).

"""

'\nAssignment for You:\n\n1. Modify the Matrix: Change the matrix A to [[3, 1], [1, 3]] and rerun the code. What are the new eigenvalues and eigenvectors?\n\n2. Verify Manually: Pick one eigenvector from the result and multiply it by A using pen-and-paper. Check if it equals the eigenvalue times the eigenvector.\n\n3. Real-World Connection: Think of a scenario where finding these "special directions" (eigenvectors) might be useful (e.g., in computer graphics or physics).\n\n'

In [11]:
import numpy as np

A = np.array([[3, 1],
              [1, 3]])


eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:")
print(A)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

#Eigenvalues are [4, 2]
#Eigenvectors are [[ 0.70710678, -0.70710678], [ 0.70710678, 0.70710678]]

eigenvector = eigenvectors[:, 0]
eigenvalue = eigenvalues[0]

result_one = np.dot(A, first_eigenvector)
result_two = eigenvalue * eigenvector

#We see that multiplying the eigenvector by A is equal to multiplying the eigenvector with the eigenvalue

print(result_one)
print(result_two)


"""
Principal Component Analysis is a critical dimensionality reduction technique in machine learning that relies on eigenvectors and eigenvalues.
PCA is useful in ML because it reduces the complexity of datasets, allowing for faster training with improved model performance.

Eigenvectors and eigenvalues are the basis of PCA.

Eigenvectors can help describe the direction of spread to reduce complexity- they are the principal components.
Eigenvalues can help quanitfy that spread/ variance.
"""

Matrix A:
[[3 1]
 [1 3]]

Eigenvalues: [4. 2.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[2.82842712 2.82842712]
[2.82842712 2.82842712]


'\nPrincipal Component Analysis is a critical dimensionality reduction technique in machine learning that relies on eigenvectors and eigenvalues.\nPCA is useful in ML because it reduces the complexity of datasets, allowing for faster training with improved model performance.\n\nEigenvectors and eigenvalues are the basis of PCA.\n\nEigenvectors can help describe the direction of spread to reduce complexity- they are the principal components.\nEigenvalues can help quanitfy that spread/ variance.\n'